# Generated by Django 4.0.4 on 2022-06-21 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CNPJ',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(max_length=8),
        ),
    ]
